### PR TITLE
runtime-sdk/modules/evm: Add more tests and fixes

### LINKED ISSUE #428: runtime-sdk/modules/evm: Add unit tests
Unit tests should be added to test all the new EVM code, including the EVM caller address derivation.

### PR DESCRIPTION
**Pull request by abukosek**
Closes #428.

### CODE REVIEW

File: tests/e2e/simpleevmtest.go [hunk 1]
```diff
@@ -210,7 +272,7 @@ func SimpleEVMTest(sc *RuntimeScenario, log *logging.Logger, conn *grpc.ClientCo
 	signer := testing.Dave.Signer
 	e := evm.NewV1(rtc)
 
-	value, err := hex.DecodeString(strings.Repeat("0", 64))
+	value, err := hex.DecodeString(strings.Repeat("0", 64-1) + "1")
```
Comment (kostko) [inline tests/e2e/simpleevmtest.go:275]: Maybe add a comment that this is transferring 1 base unit into the called contract?

**Review by kostko — APPROVED** [review]
