### PR TITLE
rofl-app-core: Retry registration using exponential backoff

### LINKED ISSUE #2232: Add exponential backoff for failing registrations
Currently the ROFL app will try to re-register on each round in case the registration fails. It should instead use exponential backoff.

### PR DESCRIPTION
**Pull request by kostko**
Fixes #2232

### CODE REVIEW

File: rofl-app-core/src/registration.rs [hunk 1]
```diff
@@ -80,20 +78,39 @@ where
...
+                        "err" => ?err,
+                    );
+                }
+
+                result.map_err(backoff::Error::transient)
+            })
+            .await;
+
+            match result {
+                Ok(epoch) => last_registration_epoch = Some(epoch),
```
Comment (peternose) [inline rofl-app-core/src/registration.rs:99]: Do we need to clear the `notify` buffer after successful registration, as otherwise we will register twice in a row?

Comment (kostko) [reply rofl-app-core/src/registration.rs:99]: Why, the `refresh_registration` method should check before registering again?

Comment (peternose) [reply rofl-app-core/src/registration.rs:99]: Did know that was implemented in `refresh_registration`. Looks fine this way.

**Review by peternose — APPROVED** [review]
